name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure additional swap space
        run: |
          sudo diskutil erasevolume HFS+ "swap" $(sudo hdiutil attach -nomount ram://8388608) # Creates 4GB swap
          sudo swapon /dev/disk$(diskutil list | grep swap | awk '{print $1}' | tr -d '*')      

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: |
          make install

      - name: Run linting
        run: |
          make lint

      - name: Run formatting check
        run: |
          make format

      - name: Run tests
        run: |
          make test
