name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure additional swap space
        run: |
           sudo dd if=/dev/zero of=/private/var/vm/swapfile bs=1024m count=4
           sudo chmod 0600 /private/var/vm/swapfile
           sudo dynamic_pager -F /private/var/vm/swapfile      

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: |
          make install

      - name: Run linting
        run: |
          make lint

      - name: Run formatting check
        run: |
          make format

      - name: Run tests
        run: |
          make test
